/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@protocol GBSharedThriftServiceGoonbeeSharedThriftService <NSObject>
- (NSString *) alive;  // throws TException
@end

@interface GBSharedThriftServiceGoonbeeSharedThriftServiceClient : NSObject <GBSharedThriftServiceGoonbeeSharedThriftService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface GBSharedThriftServiceGoonbeeSharedThriftServiceProcessor : NSObject <TProcessor> {
  id <GBSharedThriftServiceGoonbeeSharedThriftService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithGoonbeeSharedThriftService: (id <GBSharedThriftServiceGoonbeeSharedThriftService>) service;
- (id<GBSharedThriftServiceGoonbeeSharedThriftService>) service;
@end

@interface GBSharedThriftServiceGoonbeeSharedThriftServiceConstants : NSObject {
}
@end
