/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"

#import "GoonbeeSharedThriftService.h"

enum GBPushResponseStatus {
  ResponseStatus_SUCCESS = 0,
  ResponseStatus_GENERIC = 1,
  ResponseStatus_MALFORMED_REQUEST = 2,
  ResponseStatus_AUTHENTICATION = 3,
  ResponseStatus_AUTHORIZATION = 4,
  ResponseStatus_PHASED_OUT = 5
};

enum GBPushRangeDirection {
  RangeDirection_FORWARDS = 0,
  RangeDirection_BACKWARDS = 1
};

enum GBPushPushTokenType {
  PushTokenType_APNS = 0,
  PushTokenType_GCM = 1
};

@interface GBPushRequestError : NSException <TBase, NSCoding> {
  int __status;
  NSString * __message;

  BOOL __status_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=status, setter=setStatus:) int status;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithStatus: (int) status message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) status;
- (void) setStatus: (int) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface GBPushRange : NSObject <TBase, NSCoding> {
  int __direction;
  int32_t __index;
  int32_t __length;

  BOOL __direction_isset;
  BOOL __index_isset;
  BOOL __length_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=direction, setter=setDirection:) int direction;
@property (nonatomic, getter=index, setter=setIndex:) int32_t index;
@property (nonatomic, getter=length, setter=setLength:) int32_t length;
#endif

- (id) init;
- (id) initWithDirection: (int) direction index: (int32_t) index length: (int32_t) length;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) direction;
- (void) setDirection: (int) direction;
#endif
- (BOOL) directionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) index;
- (void) setIndex: (int32_t) index;
#endif
- (BOOL) indexIsSet;

#if !__has_feature(objc_arc)
- (int32_t) length;
- (void) setLength: (int32_t) length;
#endif
- (BOOL) lengthIsSet;

@end

@interface GBPushPushToken : NSObject <TBase, NSCoding> {
  int __type;
  NSString * __token;

  BOOL __type_isset;
  BOOL __token_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=type, setter=setType:) int type;
@property (nonatomic, retain, getter=token, setter=setToken:) NSString * token;
#endif

- (id) init;
- (id) initWithType: (int) type token: (NSString *) token;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) type;
- (void) setType: (int) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) token;
- (void) setToken: (NSString *) token;
#endif
- (BOOL) tokenIsSet;

@end

@protocol GBPushGoonbeePushService <NSObject>
- (void) setChannelSubscriptionStatus: (GBPushPushToken *) pushToken channel: (NSString *) channel;  // throws TException
- (NSMutableArray *) subsriptions: (GBPushPushToken *) pushToken range: (GBPushRange *) range;  // throws TException
- (BOOL) subsriptionStatus: (GBPushPushToken *) pushToken channel: (NSString *) channel;  // throws TException
@end

@interface GBPushGoonbeePushServiceClient : NSObject <GBPushGoonbeePushService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface GBPushGoonbeePushServiceProcessor : NSObject <TProcessor> {
  id <GBPushGoonbeePushService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithGoonbeePushService: (id <GBPushGoonbeePushService>) service;
- (id<GBPushGoonbeePushService>) service;
@end

@interface GBPushGoonbeePushServiceConstants : NSObject {
}
@end
