//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./GoonbeeSharedThriftService_types');
//HELPER FUNCTIONS AND STRUCTURES

GBSharedThriftService.GoonbeeSharedThriftService_alive_args = function(args) {
};
GBSharedThriftService.GoonbeeSharedThriftService_alive_args.prototype = {};
GBSharedThriftService.GoonbeeSharedThriftService_alive_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GBSharedThriftService.GoonbeeSharedThriftService_alive_args.prototype.write = function(output) {
  output.writeStructBegin('GoonbeeSharedThriftService_alive_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GBSharedThriftService.GoonbeeSharedThriftService_alive_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
GBSharedThriftService.GoonbeeSharedThriftService_alive_result.prototype = {};
GBSharedThriftService.GoonbeeSharedThriftService_alive_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GBSharedThriftService.GoonbeeSharedThriftService_alive_result.prototype.write = function(output) {
  output.writeStructBegin('GoonbeeSharedThriftService_alive_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GBSharedThriftService.GoonbeeSharedThriftServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
GBSharedThriftService.GoonbeeSharedThriftServiceClient.prototype = {};
GBSharedThriftService.GoonbeeSharedThriftServiceClient.prototype.alive = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_alive();
};

GBSharedThriftService.GoonbeeSharedThriftServiceClient.prototype.send_alive = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('alive', Thrift.MessageType.CALL, this.seqid);
  var args = new GBSharedThriftService.GoonbeeSharedThriftService_alive_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GBSharedThriftService.GoonbeeSharedThriftServiceClient.prototype.recv_alive = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GBSharedThriftService.GoonbeeSharedThriftService_alive_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('alive failed: unknown result');
};
GBSharedThriftService.GoonbeeSharedThriftServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
GBSharedThriftService.GoonbeeSharedThriftServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

GBSharedThriftService.GoonbeeSharedThriftServiceProcessor.prototype.process_alive = function(seqid, input, output) {
  var args = new GBSharedThriftService.GoonbeeSharedThriftService_alive_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.alive(function (err, result) {
    var result = new GBSharedThriftService.GoonbeeSharedThriftService_alive_result((err != null ? err : {success: result}));
    output.writeMessageBegin("alive", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

